name: Deploy EPRPy Documentation

on:
  push:
    paths:
      - 'docs/source/**'
      - 'eprpy/**'
      - '.github/workflows/**'
      - 'setup.py'
      - 'pyproject.toml'
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Install dependencies
        run: |
          pip install .
          pip install sphinx
          pip install nbsphinx furo sphinx-copybutton
          pip install pygments ipython --upgrade

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html

